sudo: required
services:
    - docker
before_install:
    - docker build -t vasi1796/docker_training -f Dockerfile.dev .
script:
    - docker run vasi1796/docker_training -e CI=true npm run test -- --coverage