sudo: required
services:
    - docker
before_install:
    - docker build -t vasi1796/docker_training -f Dockerfile.dev .
script:
    - docker run vasi1796/docker_training -e CI=true npm run test -- --coverage
deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker_training"
    env: "DockerTraining-env"
    bucket-name: "elasticbeanstalk-us-east-2-262801409821"
    bucket-path: "docker_training"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY